/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_thinkdo_adater_Test */

#ifndef _Included_com_example_thinkdo_adater_Test
#define _Included_com_example_thinkdo_adater_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_thinkdo_adater_Test
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_thinkdo_adater_Test_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
